name: Publish Any Commit

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm build
      - run: API_URL=https://2ca08c2e.stackblitz-cr.pages.dev/ pnpm dlx pkg-pr-new@https://2ca08c2e.stackblitz-cr.pages.dev/stackblitz-labs/pkg.pr.new/pkg-pr-new@329
publish --yarn
